version: '3.8'

services:
  # Servicio 1: Tu Base de Datos
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=ghost_user
      - POSTGRES_PASSWORD=ghost_password
      - POSTGRES_DB=ghost_kitchen_db
    ports:
      - "5432:5432"
    # ¡Corregido! Ahora tiene los espacios correctos para pertenecer a 'db'
    command: ["postgres", "-c", "max_connections=600", "-c", "shared_buffers=256MB"]

  # Servicio 2: Tu Backend FastAPI
  backend:
    build: .
    # Cambiamos --reload por --workers 4 para multiplicar tu capacidad de respuesta
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --workers 4
    volumes:
      - .:/app  # ¡Esto permite que si editas código en Windows, se actualice en Docker!
    ports:
      - "8000:8000"
    environment:
      # Forzamos la URL interna de Docker
      - DATABASE_URL=postgresql://ghost_user:ghost_password@db:5432/ghost_kitchen_db
    depends_on:
      - db

volumes:
  postgres_data: